name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv (Python 3.12)
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Sync dependencies (dev)
        run: uv sync --all-extras --dev

      - name: Ruff lint
        run: uv run ruff check .

      - name: Type check with pyrefly
        run: uvx pyrefly check src/ tests/

      - name: Run unit tests (skip integration)
        run: uv run pytest -q -m "not integration"
