name: Release (PyPI)

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
        # IMPORTANT: this permission is mandatory for Trusted Publishing
        id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv (Python 3.12)
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.12'

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish