name: Release (PyPI)

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv (Python 3.12)
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.12'

      - name: Build
        run: uv build

      - name: Publish to PyPI (Trusted Publishing)
        run: uv publish
        env:
          # For token-based fallback, set a repo secret named PYPI_API_TOKEN and uncomment:
          # UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

